apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-dep
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: calc
  template:
    metadata:
      labels:
        app: calc
    spec:
      containers:
      - name: calc-cont
        image: IMAGE_ID
        ports:
        - containerPort: 8080
